### View(Reshape)
- 넘파이의 reshape 함수와 매우 유사한 기능을 한다.
- view를 이용해 모양을 자유자재로 바꿔줄 수 있다.

In [2]:
import numpy as np
import torch

In [3]:
t=np.array([[[0,1,2],
           [3,4,5]],
          
          [[6,7,8],
          [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape) # 2*2*3 짜리 육면체를 생각할 수 있다.

torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1,3])) # 원래 (2,2,3)이었는데 (2*2,3으로 바뀜) -1은 잘 모르겠으니 알아서 채워달라는 뜻.
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1,1,3]))# 원래 tensor와 곱만 같으면 된다. 근데 틀릴 수도 있으니까 하나는 -1로 지정.
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- dimension이 1인 차원을 자동으로 날려준다.
- squeeze(dim=?) 인 경우 해당 차원이 1이라면 없애주는 역할을 한다.

In [10]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape) #>> 차원이 (3,1) 이므로 squeeze를 쓰면 1을 날려준다.

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze())
print(ft.squeeze().shape)# 1부분을 날려서 3만 남아있다.
#ft.squeeze(dim=0)으로 한다면 dim=0은 1이 아니므로 ft 그대로이다.

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze
- squeeze랑 다르게 dim을 반드시 지정

In [13]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [15]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)# dim=0에서 1인 차원을 추가하라는 말

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [16]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape) # 1*아무거나 차원으로 바꾸라는 말

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [17]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) #1차원에 새 차원이 생기라는 말

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [18]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape) #맨 뒤에 새 차원이 생기라는 말

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting
- 텐서의 타입을 바꿔준다

In [19]:
lt=torch.LongTensor([1,2,3,4]) 
print(lt)

tensor([1, 2, 3, 4])


In [20]:
print(lt.float())#  long 타입을 float 타입으로 바꿔준다. 
# long은 정수 float은 실수

tensor([1., 2., 3., 4.])


In [21]:
bt=torch.ByteTensor([True,False, False, True]) #Boolen 형태
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [22]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate
- 이어 붙인다는 뜻이다.

In [24]:
x=torch.FloatTensor([[1,2],[3,4]]) #2*2 matrix
y=torch.FloatTensor([[5,6],[7,8]]) #2*2 matrix

print(torch.cat([x,y],dim=0)) #dim=0으로 합치니까 4*2 matirx
print(torch.cat([x,y],dim=1)) #dim=1으로 합치니까 2*4 matrix

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
- concatenation을 편리하게 이용하기 위해 몇 가지 작업을 단축시켜 놓은 것이다.

In [25]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

print(torch.stack([x,y,z])) 
print(torch.stack([x,y,z],dim=1)) #텐서를 담은 리스트, 차원을 인수로 받음.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [28]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0)) 
#원래는 이런 과정인데 stack을 이용하면 좀더 간편하다

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros
- 같은 shape에 모든 값이 1인 텐서, 모든 값이 0인 텐서 생성한다.

In [29]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [30]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In- place Operation

In [32]:
x=torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.)) # x에 2를 곱하지만 x가 바뀌지는 않는다.
print(x)
print(x.mul_(2.)) #언더바를 이용해서 사용한다. 정답값을 기존의 텐서에 넣어라.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
