In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# for reproducibility 똑같이 결과를 재현하기 위해 재현성.
torch.manual_seed(1)

In [24]:
#Training data
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data=[[0],[0],[0],[1],[1],[1]]

In [25]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [26]:
print('e^1 equals: ',torch.exp(torch.FloatTensor([1]))) 
#exponential 나타내는 함수

e^1 equals:  tensor([2.7183])


In [27]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
hypothesis=1/(1+torch.exp(-(x_train.matmul(W)+b)))
print(hypothesis)
print(hypothesis.shape) # 전부 0으로 맞춰서 기본값 0.5만 나옴.

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [28]:
print('1/(1+e^{-1}) equals: ',torch.sigmoid(torch.FloatTensor([1])))
# 시그모이드 함수에 [1] 대입한 것.

1/(1+e^{-1}) equals:  tensor([0.7311])


In [29]:
hypothesis=torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis)
print(hypothesis.shape)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [30]:
# cost 계산
-(y_train[0]*torch.log(hypothesis[0]))+(1-y_train[0])*torch.log(1-hypothesis[0])

tensor([-0.6931], grad_fn=<AddBackward0>)

In [31]:
 # cost 계산
losses=-(y_train*torch.log(hypothesis))+(1-y_train)*torch.log(1-hypothesis)
print(losses)

tensor([[-0.6931],
        [-0.6931],
        [-0.6931],
        [ 0.6931],
        [ 0.6931],
        [ 0.6931]], grad_fn=<AddBackward0>)


In [32]:
cost=losses.mean()
print(cost)

tensor(0., grad_fn=<MeanBackward1>)


In [33]:
# 지금까지 적은 수식들을 한 번에 해결.
F.binary_cross_entropy(hypothesis,y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [35]:

#모델 초기화
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

#optimizer 설정
optimizer=optim.SGD([W,b],lr=1)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    
    hypothesis=torch.sigmoid(x_train.matmul(W)+b)
    cost=F.binary_cross_entropy(hypothesis,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {: 6f}'.format(epoch,nb_epochs,hypothesis.squeeze().detach(),cost.item()))
    

Epoch    0/1000 hypothesis: tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000]) Cost:  0.693147
Epoch  100/1000 hypothesis: tensor([0.0245, 0.1484, 0.2770, 0.7954, 0.9484, 0.9834]) Cost:  0.134722
Epoch  200/1000 hypothesis: tensor([0.0080, 0.1065, 0.1632, 0.8566, 0.9769, 0.9931]) Cost:  0.080643
Epoch  300/1000 hypothesis: tensor([0.0037, 0.0822, 0.1161, 0.8888, 0.9869, 0.9965]) Cost:  0.057900
Epoch  400/1000 hypothesis: tensor([0.0021, 0.0669, 0.0902, 0.9090, 0.9916, 0.9979]) Cost:  0.045300
Epoch  500/1000 hypothesis: tensor([0.0013, 0.0564, 0.0739, 0.9229, 0.9941, 0.9986]) Cost:  0.037261
Epoch  600/1000 hypothesis: tensor([8.7256e-04, 4.8759e-02, 6.2629e-02, 9.3312e-01, 9.9567e-01, 9.9906e-01]) Cost:  0.031672
Epoch  700/1000 hypothesis: tensor([6.2087e-04, 4.2945e-02, 5.4368e-02, 9.4091e-01, 9.9668e-01, 9.9932e-01]) Cost:  0.027556
Epoch  800/1000 hypothesis: tensor([4.6039e-04, 3.8371e-02, 4.8050e-02, 9.4706e-01, 9.9737e-01, 9.9949e-01]) Cost:  0.024394
Epoch  900/1000 hyp

In [39]:
# 모델의 정확도 확인 Evaluation 과정
hypothsis=torch.sigmoid(x_train.matmul(W)+b) # 나중에는 test set을 넣음.

print(hypothesis[:5])

# 1일 확률이 0.5보다 크면 1이라고 하자.
prediction=hypothesis>=torch.FloatTensor([0.5])
print(prediction[:5])
print(y_train[:5])

# 예측이 얼마나 맞는지 확인하자
correct_prediction=prediction.float()==y_train
print(correct_prediction[:5])

tensor([[2.7711e-04],
        [3.1636e-02],
        [3.9014e-02],
        [9.5618e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)
tensor([[0],
        [0],
        [0],
        [1],
        [1]], dtype=torch.uint8)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
tensor([[1],
        [1],
        [1],
        [1],
        [1]], dtype=torch.uint8)


In [55]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1) # 오 댓글보고 고침!!
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [56]:
model=BinaryClassifier()

In [57]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/100 Cost: 0.574488 Accuracy 83.33%
Epoch   10/100 Cost: 0.498893 Accuracy 66.67%
Epoch   20/100 Cost: 0.472237 Accuracy 66.67%
Epoch   30/100 Cost: 0.396055 Accuracy 83.33%
Epoch   40/100 Cost: 0.336031 Accuracy 83.33%
Epoch   50/100 Cost: 0.283760 Accuracy 83.33%
Epoch   60/100 Cost: 0.236473 Accuracy 100.00%
Epoch   70/100 Cost: 0.194791 Accuracy 100.00%
Epoch   80/100 Cost: 0.164508 Accuracy 100.00%
Epoch   90/100 Cost: 0.148194 Accuracy 100.00%
Epoch  100/100 Cost: 0.137658 Accuracy 100.00%
