In [1]:
print("Hello World")

Hello World


In [5]:
import numpy as np
import torch

### 1D Array with Numpy

In [7]:
t=np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [9]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) # 7개의 element가 있다.

Rank of t:  1
Shape of t:  (7,)


In [11]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1]) #Element
print('t[2:5] t[4,-1] = ',t[2:5],t[4:-1]) #Slicing
print('t[:2] t[3:] = ',t[:2],t[3:]) #Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4,-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [12]:
t=np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.,], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [14]:
print('Rank of t: ',t.ndim) #2차 확인
print('Shape of t: ' ,t.shape)

Rank of t:  2
Shape of t:  (4, 3)


### 1D Array with PyTorch

In [15]:
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [16]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #shape
print(t[0],t[1],t[-1]) #Element
print(t[2:5],t[4:-1]) #Slicing
print(t[:2],t[3:]) #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [17]:
t=torch.FloatTensor([[1., 2., 3.],
                    [4., 5., 6.],
                    [7., 8., 9.],
                    [10., 11., 12.]
                    ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [18]:
print(t.dim()) #rank
print(t.size()) #shape
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting
- 사칙연산시에 차원이 일치해야한다는 규칙이 있다.
- 하지만 불가피하게 차원이 일치하지 않는 텐서의 사칙연산을 해야 한다.
- 그럴 때 자동적으로 차원을 맞춰주는 기능을 broadcasting이라 한다.

In [20]:
#Same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [21]:
#Vector + scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3]) #3->[[3,3]]자동으로 변환해서 계산.
print(m1+m2)

tensor([[4., 5.]])


In [22]:
#2 x 1 vector + 1 x 2 vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]]) #둘다 2x2로 변환해서 계산.
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication
- 딥러닝은 행렬곱이 많이 나온다.

In [24]:
print()
print('-----------')
print('Mul vs Matmul')
print('-----------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape)
print('Shape of Matrix 2: ',m2.shape)
print(m1.matmul(m2))
print(m1*m2)
print(m1.mul(m2))


-----------
Mul vs Matmul
-----------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [25]:
t=torch.FloatTensor([1,2])
print(t.mean())# 1,2의 평균

tensor(1.5000)


In [26]:
#Can't use mean() on integers
t=torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [27]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.mean()) # 전체 4개 원소의 평균
print(t.mean(dim=0)) #0차원에 대한 평균, 각 열벡터 내에서의 평균
print(t.mean(dim=1)) #1치원에 대한 평균, 각 행벡터 내에서의 평균
print(t.mean(dim=-1)) #마지막 차원에 대한 평균이므로 1차원에 대한 평균과 같다.

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [30]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.sum())
print(t.sum(dim=0))# 이것도 mean이랑 같이 열 내부 원자끼리 합
print(t.sum(dim=1))# 행 내부 원자끼리 합
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax
- max는 최댓값, Argmax는 최댓값의 인덱스 값 

In [32]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.max()) #4개 원소중 가장 큰 값

tensor(4.)


In [37]:
print(t.max(dim=0)) #max만 구해도 argmax값을 같이 리턴해준다.
print('Max: ',t.max(dim=0)[0])
print('Argmax: ',t.max(dim=0)[1])

(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [38]:
print(t.max(dim=1))
print(t.max(dim=-1))

(tensor([2., 4.]), tensor([1, 1]))
(tensor([2., 4.]), tensor([1, 1]))
